services:
  ## Infrastructure Extensions
  unity-auth-db:
    container_name: unity-auth-db
    networks:
      - unity-network
    extends:
      file: UnityAuth/docker-compose.db.yml
      service: unity-auth-db

  ## API Extensions
  unity-auth-api:
    container_name: unity-auth-api
    networks:
      - unity-network
    extends:
      file: UnityAuth/docker-compose.api.yml
      service: unity-auth-api
    depends_on:
      unity-auth-db:
        condition: service_healthy

  ## UI Service
  unity-auth-ui:
    container_name: unity-auth-ui
    build:
      dockerfile: DockerfileFrontend
      context: .
    restart: no
    environment:
      VITE_BACKEND_URL: http://unity-auth-api:8080
    ports:
      - "3001:80"

networks:
  default:
    name: unity-network
    external: true
  unity-network:
    external: true
